"""initial schema

Revision ID: 1be63c0464e3
Revises: 
Create Date: 2026-07-11 15:38:57.542282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.types


# revision identifiers, used by Alembic.
revision: str = '1be63c0464e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'google', 'openrouter', 'openai_compatible', name='aiprovider', native_enum=False), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('api_key_encrypted', app.models.types.Encrypted(length=1024), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('monthly_budget_usd', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('attachments',
    sa.Column('owner_type', sa.Enum('mail_item', 'outbound_item', 'pickup', name='attachmentownertype', native_enum=False), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('label_photo', 'extra_photo', 'damage_photo', 'pickup_signature', 'pickup_photo', name='attachmentkind', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_owner_id'), 'attachments', ['owner_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_type', sa.Enum('user', 'api_key', 'system', name='actortype', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('diff_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('carriers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('postal', 'courier', 'freight', 'store', 'messenger', 'other', name='carrierkind', native_enum=False), nullable=False),
    sa.Column('tracking_pattern', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carriers_slug'), 'carriers', ['slug'], unique=True)
    op.create_table('departments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('manager_employee_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['employees.id'], name='fk_dept_manager_employee', use_alter=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ocr_jobs',
    sa.Column('attachment_ids', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='ocrstatus', native_enum=False), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('barcode_results', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_jobs_status'), 'ocr_jobs', ['status'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'counter', 'employee', 'viewer', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', app.models.types.Encrypted(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('webhook_endpoints',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', app.models.types.Encrypted(length=255), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('ext', sa.String(length=32), nullable=True),
    sa.Column('email', app.models.types.Encrypted(length=255), nullable=True),
    sa.Column('phone', app.models.types.Encrypted(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='employeestatus', native_enum=False), nullable=False),
    sa.Column('pickup_code', sa.String(length=8), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pickup_code')
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_table('mail_items',
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('tracking_no', sa.String(length=64), nullable=True),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('mail_type', sa.Enum('letter', 'document', 'parcel', 'box', 'pallet', name='mailtype', native_enum=False), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_org', sa.String(length=255), nullable=True),
    sa.Column('sender_phone', app.models.types.Encrypted(length=255), nullable=True),
    sa.Column('recipient_employee_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_name_raw', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('received', 'notified', 'picked_up', 'returned', 'forwarded', 'unclaimed', 'destroyed', name='mailstatus', native_enum=False), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('is_cod', sa.Boolean(), nullable=False),
    sa.Column('cod_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refrigeration', sa.Enum('none', 'chilled', 'frozen', name='refrigeration', native_enum=False), nullable=False),
    sa.Column('size_note', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remind_count', sa.Integer(), nullable=False),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_by_name', sa.String(length=255), nullable=True),
    sa.Column('pickup_method', sa.Enum('signature', 'pickup_code', 'qr', name='pickupmethod', native_enum=False), nullable=True),
    sa.Column('ocr_job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['ocr_job_id'], ['ocr_jobs.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_items_item_no'), 'mail_items', ['item_no'], unique=True)
    op.create_index(op.f('ix_mail_items_recipient_employee_id'), 'mail_items', ['recipient_employee_id'], unique=False)
    op.create_index(op.f('ix_mail_items_status'), 'mail_items', ['status'], unique=False)
    op.create_index(op.f('ix_mail_items_tracking_no'), 'mail_items', ['tracking_no'], unique=False)
    op.create_table('notification_bindings',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('line', 'telegram', 'slack', 'discord', 'email', 'webhook', 'webpush', name='notificationchannel', native_enum=False), nullable=False),
    sa.Column('address', app.models.types.Encrypted(length=1024), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_bindings_employee_id'), 'notification_bindings', ['employee_id'], unique=False)
    op.create_table('outbound_items',
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('applicant_employee_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('to_name', sa.String(length=255), nullable=True),
    sa.Column('to_org', sa.String(length=255), nullable=True),
    sa.Column('to_address', app.models.types.Encrypted(length=1024), nullable=True),
    sa.Column('to_phone', app.models.types.Encrypted(length=255), nullable=True),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('tracking_no', sa.String(length=64), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment', sa.Enum('company', 'dept_code', 'personal', name='outboundpayment', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('pending', 'shipped', 'delivered', 'exception', name='outboundstatus', native_enum=False), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_items_item_no'), 'outbound_items', ['item_no'], unique=True)
    op.create_index(op.f('ix_outbound_items_status'), 'outbound_items', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_items_tracking_no'), 'outbound_items', ['tracking_no'], unique=False)
    op.create_table('notifications',
    sa.Column('mail_item_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('line', 'telegram', 'slack', 'discord', 'email', 'webhook', 'webpush', name='notificationchannel', native_enum=False), nullable=False),
    sa.Column('template', sa.Enum('received', 'reminder', 'overdue', name='notificationtemplate', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', 'dead', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['mail_item_id'], ['mail_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_employee_id'), 'notifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_notifications_mail_item_id'), 'notifications', ['mail_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_mail_item_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_employee_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_outbound_items_tracking_no'), table_name='outbound_items')
    op.drop_index(op.f('ix_outbound_items_status'), table_name='outbound_items')
    op.drop_index(op.f('ix_outbound_items_item_no'), table_name='outbound_items')
    op.drop_table('outbound_items')
    op.drop_index(op.f('ix_notification_bindings_employee_id'), table_name='notification_bindings')
    op.drop_table('notification_bindings')
    op.drop_index(op.f('ix_mail_items_tracking_no'), table_name='mail_items')
    op.drop_index(op.f('ix_mail_items_status'), table_name='mail_items')
    op.drop_index(op.f('ix_mail_items_recipient_employee_id'), table_name='mail_items')
    op.drop_index(op.f('ix_mail_items_item_no'), table_name='mail_items')
    op.drop_table('mail_items')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_ocr_jobs_status'), table_name='ocr_jobs')
    op.drop_table('ocr_jobs')
    op.drop_table('departments')
    op.drop_index(op.f('ix_carriers_slug'), table_name='carriers')
    op.drop_table('carriers')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attachments_owner_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('api_keys')
    op.drop_table('ai_provider_configs')
    # ### end Alembic commands ###
